### ISSUE TITLE
Problem including it as a library

### ISSUE THREAD

**Issue by jcamilo721** [ggmod/angular-2-data-table#62]
I just added angular-4-data-table and I got this error:

ERROR in ./node_modules/angular-4-data-table/src/index.ts
Module build failed: Error: /Users/juan/Projects/loyal-guru-app-owner-v2/node_modules/angular-4-data-table/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfigvia the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/juan/Projects/loyal-guru-app-owner-v2/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:663:23)
    at plugin.done.then (/Users/juan/Projects/loyal-guru-app-owner-v2/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:178:7)
 @ ./src/app/app.module.ts 49:29-60
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

I can not include it as a library.
Let me know if it is something that I am doing wrong or is it a real issue,

Thank you and have a good day !
Juan

**Comment by parmindersingh1** [comment]
i am also getting same error
